### ISSUE TITLE
zkg runs tests before installing deps

### ISSUE THREAD

**Issue by bbannier** [zeek/package-manager#106]
Currently `zkg` runs package tests before installing dependencies. If the tests require a dependency as well they could fail unintuitively.

```
❯ zkg install spicy-analyzers
The following packages will be INSTALLED:
  zeek/zeek/spicy-analyzers (v0.2.12)

The following dependencies will be INSTALLED:
  zeek/zeek/spicy-plugin (v1.1.0)

Proceed? [Y/n] y
Running unit tests for "zeek/zeek/spicy-analyzers"
error: failed to run tests for zeek/zeek/spicy-analyzers: package build_command failed, see log in /home/benjamin.bannier/.zkg/logs/spicy-analyzers-build.log
Proceed to install anyway? [N/y] n
Abort.
```

The test fails in its build step here since a tool from the dependency is not yet installed,

```
make[2]: *** No rule to make target `../analyzer/file/png/spicyz', needed by `spicy-modules/png.hlto'.  Stop.
make[1]: *** [analyzer/file/png/CMakeFiles/PNG.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target `../analyzer/file/pe/spicyz', needed by `spicy-modules/pe.hlto'.  Stop.
make[1]: *** [analyzer/file/pe/CMakeFiles/PE.dir/all] Error 2
make: *** [all] Error 2
```

I would have expected the dependencies to be available when the package tests are run.

**Comment by jsiwek** [comment]
Here's a couple branches which may help as a starting point and that I seemingly used to successfully complete a `zkg install spicy-analyzers`:

* https://github.com/zeek/package-manager/compare/topic/jsiwek/gh-106-improve-test-staging-env-and-order
* https://github.com/zeek/spicy-analyzers/compare/topic/jsiwek/zkg-issue-106

Some notes about how zkg testing works that may conflict with expectations of how things get installed:

* There was a desire for it to be possible to run package tests without actually installing packages.  That's the `zkg test` command.

* To avoid unintentional alterations to package installation environment, packages get installed into a separate/disposable "staging" location for purpose of running their tests.

* When running tests, `zkg` will modify some environment variables (`ZEEKPATH` and `ZEEK_PLUGIN_PATH`) to account for the package residing in the temporary staging dir.

* There was a desire for `zkg install` to automatically run package tests (e.g. check all tests pass before trying to actually install packages).  It currently re-uses mostly the same logic as `zkg test`, so it will still do all the same staging-methodology.  That may help premature alterations to installation environment in case tests actually fail.  Maybe it's desired to do things different and first install packages, then run tests, then roll everything back after any failure, but in the example patches, I kept using the current approach of temporary staging areas.

Here's a list of things I found problematic:

* `zkg` didn't account for the `executables` metadata being depended on by other packages during builds/tests.  This could be addressed like what I did in the example patches: pass along desired environment modifications to staging/testing logic, but in addition to `ZEEKPATH` and `ZEEK_PLUGIN_PATH`, also provide a modified `PATH` so `executables` are usable.

* The `spicy-analyzers` use of `SPICYZ` in `build_command` assumes that `spicy-plugin` will already be "installed".  That's not true while running tests -- it will be at the "staging" location instead.  In the example patch, I modified the semantics of `SPICYZ` to allow fallback to a `PATH` search in case it doesn't actually exist (alternatively, you might change `build_command` to do the existence check before even setting `SPICYZ`).

* The `btest` environment for `spicy-analyzers` was overwriting the `ZEEK_PLUGIN_PATH` that `zkg` tried to provide for the purpose of running tests within the staging area.  I made it avoid that in the example patch.

* The order in which `zkg` does package test/install operations doesn't fully take the dependency hierarchy into account (oops).  It does solve a dependency graph to find a set of packages that satisfy some requirements, but then doesn't necessarily use that set of packages to form an ordered list which would ensure children are handled before parents.  In the example patch, I did a simple change that maybe only works for shallow dependency hierarchies, but not deep ones.  I left TODO comments at the relevant points.  May also be worth double-checking all other usages of `validate_dependencies()` to see if they'll need changes (I think maybe not... but `cmd_upgrade()` was one I found tricky/unsure).

* I guess `zkg` is lacking a btest to cover the case where the test/build of a package meaningfully relies on a dependency.  Otherwise the ordering issue may have got caught earlier, so worth adding tests while fixing this issue (my example branches didn't).

**Comment by ckreibich** [comment]
Let me grab this one. Thanks a bunch @jsiwek for the context and investigation. Seems its clear that we should fully follow the dependency chains to test & install dependees first.

I'll dig into the details and follow up.
