### ISSUE TITLE
Consider always failing `install` if not skipped tests fail

### ISSUE THREAD

**Issue by bbannier** [zeek/package-manager#137]
One can currently use `install`'s `--force` flag to disable interactive confirmations,
```
--force              Don't prompt for confirmation or user variables.
```

One uses this flag to skip the interactive confirmation during normal install:
```console
$ zkg install spicy-plugin
The following packages will be INSTALLED:
  zeek/zeek/spicy-plugin (v1.3.17)

Proceed? [Y/n]
```

This has the possibly surprising effect of installing the package even if its `test_command` failed. I would argue this is surprising since one can already skip tests during installation with `--skiptests` if they are e.g., known to fail.

If `build_command` fails the installation process fails with an error code, and it might be much simpler if `test_command` behaved the same way. This would allow to use `--force` for non-interactive installations. Currently this requires scripting the possible interactive queries, e.g., to say `Y` to the confirm the installation and `N` to abort after failed tests one would use

```console
$ echo 'Y\nN' | zkg install spicy-plugin
```
Without `N` here `zkg` would forever wait for input while `--force` would imply always `Y`.
If a failing `test_command` would abort the installation one could simply use
```console
$ zkg install spicy-plugin --force
```

**Comment by JustinAzoff** [comment]
Yeah I think the semantics we really want for `--force` are more like `--non-interactive`.  The main difference being that ``--force` currently is like entering "Y" at all prompts but `--non-interactice` would be like just pressing enter at any prompt and accepting the sane default.

**Comment by awelzel** [comment]
@J-Gras reports that zkg-install-action CI currently passes even if a package has a test with a failing test, because `zkg install` is invoked with `--force`:

https://github.com/zeek/action-zkg-install/blob/055630f5a10c7f26a8dc734d321cee90ff1258bb/scripts/zkg.sh#L41

zeekorg Slack: https://zeekorg.slack.com/archives/CTGDG83B8/p1681667397916089
pipeline: https://github.com/J-Gras/zeek-test-pkg/actions/runs/4714572330/jobs/8361011947#step:4:99


> I would argue this is surprising since one can already skip tests during installation with --skiptests if they are e.g., known to fail.
> [...]
I agree. I wonder if we can/should change the behavior. Regardless of `--force` usage, a failing test can't be forced away and only worked around via `--skiptests`.

We could also do a `-y` that has a more sane "fails on failing tests" behavior. `apt-get -y` isn't automatic "yes to anything":
```
       -y, --yes, --assume-yes
           Automatic yes to prompts; assume "yes" as answer to all prompts and run non-interactively. If an
           **undesirable situation**, such as changing a held package, trying to install an unauthenticated package or
           removing an essential package occurs then apt-get will abort. Configuration Item: APT::Get::Assume-Yes.
```

**Comment by bbannier** [comment]
> I wonder if we can/should change the behavior. Regardless of `--force` usage, a failing test can't be forced away and only worked around via `--skiptests`.

I would say we should (that's why I opened the ticket). I'd argue that this would be okay from an API stability point of view since installing the ability to install with broken tests is an unintended side effect of `--force` when we already have a proper feature to enable that (`--skiptests`).
