### ISSUE TITLE
--ignore-dirty-git not behaving as expected

### ISSUE THREAD

**Issue by awelzel** [zeek/package-manager#163]
Starting a new package with lots of `--ignore-dirty-git` excitement and then being very confused that a `zkg install .` of a dirty repository installs not the dirty version, but the version of the most recent commit only.

The same applies to zkg.meta: Changing the `depends` line is only in effect after committing the changes.

That seems very unexpected, confusing and probably wasn't the idea?

**Comment by timwoj** [comment]
Well that's definitely not ideal. Why wouldn't zkg just install the plugin directly out of the directory it was pointed at? That's very counter-intuitive.

**Comment by timwoj** [comment]
As far as I can tell, zkg reclones the package no matter what you do. It pulls the repo information from the local clone, but then reclones it into the staging directory before installation (`var/lib/zkg/clones/package`). There's an argument that can be passed into `zeekpkg.Manager._install` to tell it to use an existing clone, but that's still pointing at the directory in staging, not at the one you pointed at from the install command.

**Comment by timwoj** [comment]
One easy fix would be something like this:

```
diff --git a/zeekpkg/_util.py b/zeekpkg/_util.py
index ffdac93..86c06c2 100644
--- a/zeekpkg/_util.py
+++ b/zeekpkg/_util.py
@@ -123,7 +123,9 @@ def find_sentence_end(s):
 
 
 def git_clone(git_url, dst_path, shallow=False):
-    if shallow:
+    if os.path.isabs(git_url):
+        copy_over_path(git_url, dst_path)
+    elif shallow:
         try:
             git.Git().clone(
                 git_url, dst_path, "--no-single-branch", recursive=True, depth=1
```

That would force `Manager._stage` to copy over the path from the arguments as if it was a repo, but should still work if someone passes git URL.

**Comment by awelzel** [comment]
I think for 3.0 we should revert `--ignore-dirty-git`.

**Comment by ckreibich** [comment]
I finally spent some time thinking about this so here are some suggestions for moving this forward.

Regarding zkg's behavior: yep it always makes internal clones of any repo it works with. It uses two such clones: one in the scratch folder, to figure out basic properties of a package. (If you say `zkg -vvv install ...` you can see that this clone happens before the user is even prompted to continue with the actual installation.) A second clone into the packages folder serves as the "staging area" for installation. It's from this clone that the actual package installation takes place, i.e., the copying into `share/zeek/site/packages` etc.

I think the goal of `--ignore-dirty-git` (or whatever it's called in the next iteration) should be to allow people to work locally on packages without the usual rigor of git and proper content management. What this should _not_ provide is a general shortcut to bypass "the annoying git stuff" — for example, understanding what a dirty clone is.

I think we should at least explore what it would take to work with a "raw" local source tree, without git (even though it might well be a git repo). I mean this strictly for development — no ditching of git through the backdoor. I think this approach would have a couple of benefits:
- Since we rely on git for versioning, such code would naturally be unversioned and transient.
- zkg could automatically enforce that you can only install one such devel snapshot at a time, and it could treat this as a fourth way to identify a package "version" (alongside tag, branch, and commit).
- This would imply that such transient development states aren't suitable in dependency chains, which likely is a win too. I.e., you'd only be using this development approach when you're working on the current package as a "leaf", or when you're working on dependent packages similarly locally, with actual version dependencies to fall into place later.
- Since this state would exist outside of git, it couldn't accidentally be pushed to a remote repo. Once you're ready to push, you'd still need to start thinking about what you want to have in your repo — as you should. Nothing would stop you from committing things locally etc to structure your dev workflow, that remains up to you.
- zkg already knows pretty well what matters for installation via the relevant zkg.meta fields (scripts, build_command, etc), so we'd mostly be special-casing (1) file transfer (recursive local tree copies instead of git clones) and versioning logic.

What do you guys think? If this proves too hairy, we could try to find some middle ground that still uses a particular git branch/tag/whatever as a "developmenet parking lot" for everything in your local tree. The danger I see with that approach is that somehow this parking lot ends up full of junk that gets pushed and forever bloats the repo.

I agree that until we've resolved the above, we should revert `--ignore-dirty-git`.
