### ISSUE TITLE
Accept user_vars via an argument

### ISSUE THREAD

**Issue by JonZeolla** [zeek/package-manager#39]
`bro-pkg` should be able to accept user_vars as a command line argument, and not just interactively or via a config file.

CC: @JustinAzoff

**Comment by jsiwek** [comment]
Note that you should also be able to use environment variables to specify the desired values of `user_vars` (at least I wrote docs that claim it works). That seems like it would be able to do everything you could with an argument approach, so I may close this unless there's more explanation of why/when it's better to use command line args instead of env. vars.

**Comment by JonZeolla** [comment]
That works for me, closing the ticket.
